"""Add word_column as nullable to word_definition

Revision ID: d9da4a7bb619
Revises: d35f9d08f57b
Create Date: 2025-05-10 15:06:46.172930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9da4a7bb619'
down_revision: Union[str, None] = 'd35f9d08f57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_definition', sa.Column('word', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_definition', 'word')
    # ### end Alembic commands ###
